
// This file has been generated by the GUI designer. Do not modify.
namespace BKTMManager
{
	public partial class BKTMApp
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action DevicesAction;

		private global::Gtk.Action ComponentsAction;

		private global::Gtk.Action RoomsAction;

		private global::Gtk.Action ResellersAction;

		private global::Gtk.Action HelpAction;

		private global::Gtk.Action applyAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar1;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview1;

		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget BKTMManager.BKTMApp
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.DevicesAction = new global::Gtk.Action("DevicesAction", global::Mono.Unix.Catalog.GetString("Devices"), null, null);
			this.DevicesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Devices");
			w1.Add(this.DevicesAction, null);
			this.ComponentsAction = new global::Gtk.Action("ComponentsAction", global::Mono.Unix.Catalog.GetString("Components"), null, null);
			this.ComponentsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Components");
			w1.Add(this.ComponentsAction, null);
			this.RoomsAction = new global::Gtk.Action("RoomsAction", global::Mono.Unix.Catalog.GetString("Rooms"), null, null);
			this.RoomsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Rooms");
			w1.Add(this.RoomsAction, null);
			this.ResellersAction = new global::Gtk.Action("ResellersAction", global::Mono.Unix.Catalog.GetString("Resellers"), null, null);
			this.ResellersAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Resellers");
			w1.Add(this.ResellersAction, null);
			this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
			w1.Add(this.HelpAction, null);
			this.applyAction = new global::Gtk.Action("applyAction", null, null, "gtk-apply");
			w1.Add(this.applyAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Sensitive = false;
			this.Name = "BKTMManager.BKTMApp";
			this.Title = global::Mono.Unix.Catalog.GetString("BKTMManager");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child BKTMManager.BKTMApp.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='DevicesAction' action='DevicesAction'/><menu name='ComponentsAction' action='ComponentsAction'/><menu name='RoomsAction' action='RoomsAction'/><menu name='ResellersAction' action='ResellersAction'/><menu name='HelpAction' action='HelpAction'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add(this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'applyAction\' action=\'applyAction\'/><" +
					"/toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add(this.treeview1);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w5.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add(this.statusbar1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 652;
			this.DefaultHeight = 474;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		}
	}
}
