
// This file has been generated by the GUI designer. Do not modify.
namespace BKTMManager
{
	public partial class Login
	{
		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label username;

		private global::Gtk.Entry entry10;

		private global::Gtk.Label password;

		private global::Gtk.Entry entry8;

		private global::Gtk.Button buttonAbort;

		private global::Gtk.Button buttonLogin;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget BKTMManager.Login
			this.Name = "BKTMManager.Login";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child BKTMManager.Login.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Login");
			w1.Add(this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1[this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(24));
			// Container child vbox5.Gtk.Box+BoxChild
			this.username = new global::Gtk.Label();
			this.username.Name = "username";
			this.username.LabelProp = global::Mono.Unix.Catalog.GetString("username");
			this.vbox5.Add(this.username);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.username]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '●';
			this.vbox5.Add(this.entry10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.entry10]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.password = new global::Gtk.Label();
			this.password.Name = "password";
			this.password.LabelProp = global::Mono.Unix.Catalog.GetString("password");
			this.vbox5.Add(this.password);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.password]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.Visibility = false;
			this.entry8.InvisibleChar = '●';
			this.vbox5.Add(this.entry8);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.entry8]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add(this.vbox5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1[this.vbox5]));
			w7.Position = 1;
			w7.Fill = false;
			// Internal child BKTMManager.Login.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonAbort = new global::Gtk.Button();
			this.buttonAbort.CanDefault = true;
			this.buttonAbort.CanFocus = true;
			this.buttonAbort.Name = "buttonAbort";
			this.buttonAbort.UseUnderline = true;
			this.buttonAbort.Label = global::Mono.Unix.Catalog.GetString("Abort");
			this.AddActionWidget(this.buttonAbort, -2);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8[this.buttonAbort]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonLogin = new global::Gtk.Button();
			this.buttonLogin.CanDefault = true;
			this.buttonLogin.CanFocus = true;
			this.buttonLogin.Name = "buttonLogin";
			this.buttonLogin.UseUnderline = true;
			this.buttonLogin.Label = global::Mono.Unix.Catalog.GetString("Login");
			this.AddActionWidget(this.buttonLogin, -3);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8[this.buttonLogin]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
